Analysis #69 DC vacant lot analysis
NeighborhoodInfoDC/RegHsg pull request #74
Opened 2019-03-04 18:25 UTC by maggiesu0725

2019-03-04 18:30 UTC, maggiesu0725 commented
@lhendey I'm still working on reprojecting the parcel base geography for spatial joining instead of using the blacknight lat and lon. But since DC blacknight data zoning information is outdated, the program is a bit different than Sarah's example. I thought it would be helpful for you to just take a look at the structure and procedure so I can adjust accordingly while figuring out some programming issues. Thanks!

2019-03-04 18:45 UTC, maggiesu0725 commented
@sstrochak will you have time to take a quick look at the DC version vacant lot?

2019-03-04 18:53 UTC, sstrochak commented
@maggiesu0725 yeah, is it ready now?

2019-03-04 19:11 UTC, maggiesu0725 commented
I haven't solved the projection issue but just want to get some general feedback on quality checks. DC blacknight zoning is outdated so the part where you compared the blacknight and shapefile zoning is not applicable in this case, I also commented in the program where the original methodology is not applicable. If you could take a look at those. Thanks! @sstrochak

2019-03-04 20:23 UTC, sstrochak commented
@maggiesu0725 I can get to it either tomorrow morning or Wednesday morning, does that work?

2019-03-04 20:24 UTC, maggiesu0725 commented
Sure take your time! or if you prefer I walk you through the code sometime tomorrow. @sstrochak

2019-03-07 15:39 UTC, maggiesu0725 commented
So I've subdivided the lots with #dwelling restrictions. Could you do a final review? @sstrochak @lhendey

2019-03-12 21:28 UTC, maggiesu0725 commented
@lhendey I made all the changes and added the number of observation I got in the comment so it will be easier for you to compare,

2019-03-13 23:33 UTC, lhendey commented
@maggiesu0725 - my html file after knitting still has different #s. if you knit the markdown to html do you get the same result as me?

2019-03-14 01:03 UTC, lhendey requested changes
@maggiesu0725 see comments. 

cc @sstrochak .

2019-03-14 01:03 UTC, lhendey commented on Prog/vacant-lots-DC.Rmd
> +There are several variables we will use to calculate how many units we can put on each vacant lot.
edit this comment to reflect dc calculations

2019-03-15 16:10 UTC, maggiesu0725 commented
@lhendey  ready for review

2019-03-15 18:48 UTC, lhendey commented on Prog/vacant-lots-DC.Rmd
> +
@maggiesu0725 is this issue resolved?

2019-03-15 20:48 UTC, lhendey commented
@maggiesu0725 - i corrected the living area variable in the units_far calc and it broke the scatter plot function...

is there anyway to save the result of the get_unit_summary - i'd like to look at a few of the obs  where units_Far is getting us a lot of units to figure out whether the calc is wrong.

2019-03-15 21:07 UTC, pspauster commented on Prog/vacant-lots-DC.Rmd
> +           units_FAR= (living_area*floor_area_ratio_max)/average_unit_size,
@lhendey do you know how we would adapt this calculation if there is no lot coverage specified?

2019-03-15 21:10 UTC, maggiesu0725 commented
I added the dataset **calculateunit_data**  which should be what you are looking for. It is in the calculation section. fixed on function and reknitted the document, should not be breaking now. @lhendey

2019-03-15 21:13 UTC, maggiesu0725 commented
also exported the dataset to CSV: L:/Libraries/RegHsg/Prog/Tables/DC-vacant-lots-analysis-basedata.csv @lhendey

2019-03-15 22:05 UTC, lhendey commented
@maggiesu0725 thanks that's helpful. can you add the ssl to output?

Also - can you add units_far should be NA if floor_area_ratio_max is NA? (the zero's are trumping the units_height right now.

2019-03-15 22:23 UTC, maggiesu0725 commented
thanks, changes made. @lhendey

2019-03-20 16:00 UTC, maggiesu0725 commented
@lhendey I just knitted the document, if you want to take a look.

2019-03-28 00:26 UTC, lhendey reviewed
@maggiesu0725 

line 571 shouldn't we set jurtotal instead of jur2 to create jurcleaned?  they have different numbers of obs. 

line 621 jurzoningdata1 has less obs than jurtotal and jurcleaned. what is getting lost? can you add a comment?

2019-03-28 14:46 UTC, lhendey commented
@maggiesu0725 just pushed a few minor changes.

2019-03-28 15:22 UTC, maggiesu0725 commented
@lhendey  I added these comments int eh program as well.
line 571 shouldn't we set jurtotal instead of jur2 to create jurcleaned? they have different numbers of obs.
No we are using jur2 because jur2 has only the observations that have either parcelbase geo or blacknight coordinates and joined with the zoning shapefile to get the zoning information. 

line 621 jurzoningdata1 has less obs than jurtotal and jurcleaned. what is getting lost? can you add a comment?
I'm filtering out observations with zoning code that are not in the DC spreadsheet, because they are not going to be calculated in the next step. I might need to take the filter out.

2019-04-02 16:46 UTC, lhendey commented
@maggiesu0725 -FYI i'm working on the vacant-dc file

2019-04-02 20:47 UTC, sstrochak commented
To reclassify the addresses:
```
#create jur4 from blackknight address
jur5 <- jur4 %>% 
  filter(category_detail!="Garage") %>%
  classify_parceladdresses() %>% 
  mutate(ID = row_number()) %>% 
  mutate(address_type = ifelse(propaddress %in% c("address", "address", "address"),
                                                 "single",
                                                  address_type))
```

2019-04-03 14:50 UTC, maggiesu0725 commented
> To reclassify the addresses:
> 
> ```
> #create jur4 from blackknight address
> jur5 <- jur4 %>% 
>   filter(category_detail!="Garage") %>%
>   classify_parceladdresses() %>% 
>   mutate(ID = row_number()) %>% 
>   mutate(address_type = ifelse(propaddress %in% c("address", "address", "address"),
>                                                  "single",
>                                                   address_type))
> ```

@sstrochak what's the context of this? Is this something I need to update in the program? @lhendey

2019-04-03 15:18 UTC, lhendey commented
@maggiesu0725 - this is something i'm working on changing in the clean-dc file to get rid of lots that were incorrectly collapsing  and creating those huge # of units. cc @sstrochak

2019-04-03 22:57 UTC, maggiesu0725 commented
@lhendey ready for review.

2019-04-09 12:09 UTC, lhendey approved these changes

2019-04-09 12:09 UTC, merged