calculate risk to gentrification and flag for different stages
NeighborhoodInfoDC/RegHsg pull request #9
Opened 2018-12-20 23:52 UTC by maggiesu0725

2018-12-20 23:53 UTC, maggiesu0725 commented
@rpitingolo could you take a look at the average income variable? the change seems unbelievably large for some tracts

2018-12-21 13:08 UTC, rpitingolo commented
@maggiesu0725 which dataset in the vulnerable to gentriciation.sas program should I be looking at?

2018-12-21 15:37 UTC, maggiesu0725 commented
@rpitingolo merged and changeintime, specifically, when I run the proc means on changeintime, I get hte averagechange of income for washington region during 2000-2016 is 41637, which is high (maybe not?)

2018-12-21 15:42 UTC, maggiesu0725 commented
@rpitingolo I didn't adjust for inflation.

2018-12-21 21:57 UTC, maggiesu0725 commented
@lhendey see %dollar_convert part

2019-01-02 21:56 UTC, maggiesu0725 commented
@lhendey @rpitingolo the program for Lisa Bates typology of gentrification analysis. Might need changes, but main part ready for review

2019-01-03 14:29 UTC, lhendey requested changes
@maggiesu0725 - please see comments here and in the word doc i emailed. cc @rpitingolo

2019-01-03 18:36 UTC, maggiesu0725 commented on Prog/Vulnerable to gentrification.sas
> +deltarenter = numrenteroccupiedhu_&_years.- sprntoc0;
yes

2019-01-03 18:58 UTC, maggiesu0725 commented on Prog/Vulnerable to gentrification.sas
> +/*median for 2016: percentwhite:0.44 percentrenter: 0.38 percentcollege 0.51 averageincome 123451*/
Do you mean 0.4 instead of 0.44?

2019-01-03 19:00 UTC, lhendey commented on Prog/Vulnerable to gentrification.sas
> +/*median for 2016: percentwhite:0.44 percentrenter: 0.38 percentcollege 0.51 averageincome 123451*/
no - 0.443 instead of .44

2019-01-03 22:35 UTC, maggiesu0725 commented
could you take a look at Vulnerable to gentrification_Jurisdiction? I wrote a macro but it's not running, don't know where to debug. @lhendey

2019-01-09 19:10 UTC, lhendey commented
@maggiesu0725 - is this ready for review?

2019-01-09 20:22 UTC, maggiesu0725 commented
It generates the results we want, but I haven’t managed to consolidate the program to make it concise and pretty yet. @lhendey

2019-02-02 20:10 UTC, lhendey commented
@maggiesu0725 please review the changes i made in https://github.com/NeighborhoodInfoDC/RegHsg/pull/9/commits/40eb1df61227d3e37f54aa51379fdac2bf3417b0 

some were for programming efficiency and some were correcting errors.  

i'd like to also have a version that uses median HH income (not median family income) and see what the sensitivity is. if we don't have that in the currect ACS data please go through the process to add it. for 2000 please look it up for the jurisdictions in american fact finder SF3 table HCT012.  

the adjacency process will need to be repeated. i didn't make all the changes in the regionwide program (which we are no longer using, right?)

2019-02-04 18:46 UTC, maggiesu0725 commented
Thanks, I'll try. @lhendey

2019-02-08 00:06 UTC, maggiesu0725 commented
@lhendey alternative calculation by median hh income is updated. I calculated and there seems no difference between the two in terms of the final flag.

2019-02-09 17:04 UTC, lhendey commented
@maggiesu0725  - i made some changes. please run the adjacency in ARCGIS to complete the typology.

2019-02-09 17:07 UTC, lhendey commented
@maggiesu0725  - there are two demographic change flags now.

2019-02-12 16:12 UTC, maggiesu0725 commented
@lhendey I added the HH count and HH under 80% AMI.

2019-02-17 17:50 UTC, lhendey commented
@maggiesu0725 -  

I decided to use the 2013-17 data so converted all date references to macro vars in code. 

your adjacent flag file is bringing in some tracts outside the COG region please clip before. 

i've added a flag "potentialADJ" - 
if rank2017 ~=. and rank00_17 ~=. then do;
	if  rank2017<=2 & rank00_17 <=2 then potentialADJ=1; else potentialADJ=0;
	end;
else if rank2017=. or rank00_17=. then potentialADJ=.n;  

correct? 

You should use that to then determine adjacency to high 2017 or high2000-2017 tracts. I also need to be able to see that in ARC GIS. I'm not sure from what i can see on L? (to do some QC on the adjacency). '

i added code to calculate the typology for either median family income or median household income. 

i also added some code at the end to output files we could use in tables. 

I think we are really close. If you can re-run the adjacency - using the 2013-17 data and the potentialADJ flag, I can take a look at the ARC GIS file and then we can merge the updated adjacency back in and finalize this. 

Thanks!

2019-02-19 22:14 UTC, lhendey commented
@maggiesu0725 - i'm getting errors trying to run the R file.

2019-04-06 16:36 UTC, merged